// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AiGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prompt");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<int?>("TokenInput")
                        .HasColumnType("int")
                        .HasColumnName("token_input");

                    b.Property<int?>("TokenOutput")
                        .HasColumnType("int")
                        .HasColumnName("token_output");

                    b.HasKey("Id")
                        .HasName("pk_ai_generations");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_ai_generations_project_id");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_ai_generations_provider");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_ai_generations_entity_type_entity_id");

                    b.ToTable("ai_generations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("object_key");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("AssetType")
                        .HasDatabaseName("ix_assets_asset_type");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_object_key");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_assets_project_id");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid?>("FaceAssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("face_asset_id");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("FaceAssetId")
                        .HasDatabaseName("ix_characters_face_asset_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_characters_project_id");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CharacterAppearance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Accessories")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accessories");

                    b.Property<string>("BodyType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("body_type");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtraNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extra_notes");

                    b.Property<string>("EyeColor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("eye_color");

                    b.Property<string>("HairColor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hair_color");

                    b.Property<string>("HairStyle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hair_style");

                    b.Property<string>("Height")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("height");

                    b.Property<string>("SkinTone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("skin_tone");

                    b.Property<string>("TypicalOutfit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("typical_outfit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_character_appearances");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_character_appearances_character_id");

                    b.ToTable("character_appearances", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CharacterBible", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BibleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bible_json");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("generated_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_character_bibles");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_character_bibles_character_id");

                    b.ToTable("character_bibles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CharacterMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("MemoryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("memory_json");

                    b.Property<string>("MemoryScope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("memory_scope");

                    b.Property<string>("MemoryType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("memory_type");

                    b.Property<Guid?>("RelatedCharacterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("related_character_id");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("scene_id");

                    b.Property<Guid?>("StoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("story_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_character_memories");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_character_memories_character_id");

                    b.HasIndex("RelatedCharacterId")
                        .HasDatabaseName("ix_character_memories_related_character_id");

                    b.HasIndex("CharacterId", "MemoryScope")
                        .HasDatabaseName("ix_character_memories_character_id_memory_scope");

                    b.HasIndex("CharacterId", "RelatedCharacterId")
                        .HasDatabaseName("ix_character_memories_character_id_related_character_id");

                    b.ToTable("character_memories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CharacterPersonality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("background");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Goals")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("goals");

                    b.Property<string>("Quirks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("quirks");

                    b.Property<string>("SpeakingStyle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("speaking_style");

                    b.PrimitiveCollection<string>("Traits")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("traits");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_character_personalities");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_character_personalities_character_id");

                    b.ToTable("character_personalities", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CharacterRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("relationship_type");

                    b.Property<Guid?>("SinceStoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("since_story_id");

                    b.Property<Guid>("TargetCharacterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_character_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_character_relationships");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_character_relationships_character_id");

                    b.HasIndex("TargetCharacterId")
                        .HasDatabaseName("ix_character_relationships_target_character_id");

                    b.HasIndex("CharacterId", "TargetCharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_character_relationships_character_id_target_character_id");

                    b.ToTable("character_relationships", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CharacterVoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("language");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("provider");

                    b.Property<Guid?>("SampleAudioAssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sample_audio_asset_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("VoiceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("voice_id");

                    b.Property<string>("VoiceName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("voice_name");

                    b.HasKey("Id")
                        .HasName("pk_character_voices");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_character_voices_character_id");

                    b.HasIndex("SampleAudioAssetId")
                        .HasDatabaseName("ix_character_voices_sample_audio_asset_id");

                    b.ToTable("character_voices", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FinalVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("story_id");

                    b.Property<Guid?>("SubtitleAssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subtitle_asset_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VideoAssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("video_asset_id");

                    b.HasKey("Id")
                        .HasName("pk_final_videos");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("ix_final_videos_story_id");

                    b.HasIndex("SubtitleAssetId")
                        .HasDatabaseName("ix_final_videos_subtitle_asset_id");

                    b.HasIndex("VideoAssetId")
                        .HasDatabaseName("ix_final_videos_video_asset_id");

                    b.ToTable("final_videos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid?>("ImageAssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("image_asset_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("StyleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("style_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("ImageAssetId")
                        .HasDatabaseName("ix_locations_image_asset_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_locations_project_id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_projects_user_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Dialogue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dialogue");

                    b.Property<int>("DurationSec")
                        .HasColumnType("int")
                        .HasColumnName("duration_sec");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("location_id");

                    b.Property<string>("Mood")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mood");

                    b.Property<int>("SceneNumber")
                        .HasColumnType("int")
                        .HasColumnName("scene_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("story_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scenes");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_scenes_location_id");

                    b.HasIndex("StoryId", "SceneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_scenes_story_id_scene_number");

                    b.ToTable("scenes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SceneCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("scene_id");

                    b.HasKey("Id")
                        .HasName("pk_scene_characters");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_scene_characters_character_id");

                    b.HasIndex("SceneId")
                        .HasDatabaseName("ix_scene_characters_scene_id");

                    b.HasIndex("SceneId", "CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_scene_characters_scene_id_character_id");

                    b.ToTable("scene_characters", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SceneVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("int")
                        .HasColumnName("duration_sec");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<string>("JobId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("job_id");

                    b.Property<string>("PromptUsed")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prompt_used");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("scene_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StoryboardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("storyboard_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VideoAssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("video_asset_id");

                    b.HasKey("Id")
                        .HasName("pk_scene_videos");

                    b.HasIndex("SceneId")
                        .IsUnique()
                        .HasDatabaseName("ix_scene_videos_scene_id");

                    b.HasIndex("StoryboardId")
                        .HasDatabaseName("ix_scene_videos_storyboard_id");

                    b.HasIndex("VideoAssetId")
                        .HasDatabaseName("ix_scene_videos_video_asset_id");

                    b.ToTable("scene_videos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SceneVoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AudioAssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("audio_asset_id");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DialogueText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dialogue_text");

                    b.Property<decimal?>("DurationSec")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("duration_sec");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<string>("JobId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("job_id");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("scene_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scene_voices");

                    b.HasIndex("AudioAssetId")
                        .HasDatabaseName("ix_scene_voices_audio_asset_id");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_scene_voices_character_id");

                    b.HasIndex("SceneId")
                        .HasDatabaseName("ix_scene_voices_scene_id");

                    b.ToTable("scene_voices", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prompt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stories");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_stories_project_id");

                    b.ToTable("stories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Storyboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("ImageAssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("image_asset_id");

                    b.Property<string>("JobId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("job_id");

                    b.Property<string>("PromptUsed")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prompt_used");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("scene_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_storyboards");

                    b.HasIndex("ImageAssetId")
                        .HasDatabaseName("ix_storyboards_image_asset_id");

                    b.HasIndex("SceneId")
                        .IsUnique()
                        .HasDatabaseName("ix_storyboards_scene_id");

                    b.ToTable("storyboards", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AiGeneration", b =>
                {
                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("AiGenerations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_generations_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Entities.Asset", b =>
                {
                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("Assets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assets_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Entities.Character", b =>
                {
                    b.HasOne("Domain.Entities.Asset", "FaceAsset")
                        .WithMany()
                        .HasForeignKey("FaceAssetId")
                        .HasConstraintName("fk_characters_assets_face_asset_id");

                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("Characters")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_projects_project_id");

                    b.Navigation("FaceAsset");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Entities.CharacterAppearance", b =>
                {
                    b.HasOne("Domain.Entities.Character", "Character")
                        .WithOne("Appearance")
                        .HasForeignKey("Domain.Entities.CharacterAppearance", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_appearances_characters_character_id");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Entities.CharacterBible", b =>
                {
                    b.HasOne("Domain.Entities.Character", "Character")
                        .WithOne("Bible")
                        .HasForeignKey("Domain.Entities.CharacterBible", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_bibles_characters_character_id");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Entities.CharacterMemory", b =>
                {
                    b.HasOne("Domain.Entities.Character", "Character")
                        .WithMany("Memories")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_memories_characters_character_id");

                    b.HasOne("Domain.Entities.Character", "RelatedCharacter")
                        .WithMany()
                        .HasForeignKey("RelatedCharacterId")
                        .HasConstraintName("fk_character_memories_characters_related_character_id");

                    b.Navigation("Character");

                    b.Navigation("RelatedCharacter");
                });

            modelBuilder.Entity("Domain.Entities.CharacterPersonality", b =>
                {
                    b.HasOne("Domain.Entities.Character", "Character")
                        .WithOne("Personality")
                        .HasForeignKey("Domain.Entities.CharacterPersonality", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_personalities_characters_character_id");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Domain.Entities.CharacterRelationship", b =>
                {
                    b.HasOne("Domain.Entities.Character", "Character")
                        .WithMany("Relationships")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_relationships_characters_character_id");

                    b.HasOne("Domain.Entities.Character", "TargetCharacter")
                        .WithMany()
                        .HasForeignKey("TargetCharacterId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_relationships_characters_target_character_id");

                    b.Navigation("Character");

                    b.Navigation("TargetCharacter");
                });

            modelBuilder.Entity("Domain.Entities.CharacterVoice", b =>
                {
                    b.HasOne("Domain.Entities.Character", "Character")
                        .WithOne("Voice")
                        .HasForeignKey("Domain.Entities.CharacterVoice", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_voices_characters_character_id");

                    b.HasOne("Domain.Entities.Asset", "SampleAudioAsset")
                        .WithMany()
                        .HasForeignKey("SampleAudioAssetId")
                        .HasConstraintName("fk_character_voices_assets_sample_audio_asset_id");

                    b.Navigation("Character");

                    b.Navigation("SampleAudioAsset");
                });

            modelBuilder.Entity("Domain.Entities.FinalVideo", b =>
                {
                    b.HasOne("Domain.Entities.Story", "Story")
                        .WithMany("FinalVideos")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_final_videos_stories_story_id");

                    b.HasOne("Domain.Entities.Asset", "SubtitleAsset")
                        .WithMany()
                        .HasForeignKey("SubtitleAssetId")
                        .HasConstraintName("fk_final_videos_assets_subtitle_asset_id");

                    b.HasOne("Domain.Entities.Asset", "VideoAsset")
                        .WithMany()
                        .HasForeignKey("VideoAssetId")
                        .HasConstraintName("fk_final_videos_assets_video_asset_id");

                    b.Navigation("Story");

                    b.Navigation("SubtitleAsset");

                    b.Navigation("VideoAsset");
                });

            modelBuilder.Entity("Domain.Entities.Location", b =>
                {
                    b.HasOne("Domain.Entities.Asset", "ImageAsset")
                        .WithMany()
                        .HasForeignKey("ImageAssetId")
                        .HasConstraintName("fk_locations_assets_image_asset_id");

                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("Locations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_locations_projects_project_id");

                    b.Navigation("ImageAsset");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Scene", b =>
                {
                    b.HasOne("Domain.Entities.Location", "Location")
                        .WithMany("Scenes")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("fk_scenes_locations_location_id");

                    b.HasOne("Domain.Entities.Story", "Story")
                        .WithMany("Scenes")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scenes_stories_story_id");

                    b.Navigation("Location");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Domain.Entities.SceneCharacter", b =>
                {
                    b.HasOne("Domain.Entities.Character", "Character")
                        .WithMany("SceneCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("fk_scene_characters_characters_character_id");

                    b.HasOne("Domain.Entities.Scene", "Scene")
                        .WithMany("SceneCharacters")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scene_characters_scenes_scene_id");

                    b.Navigation("Character");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Domain.Entities.SceneVideo", b =>
                {
                    b.HasOne("Domain.Entities.Scene", "Scene")
                        .WithOne("Video")
                        .HasForeignKey("Domain.Entities.SceneVideo", "SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scene_videos_scenes_scene_id");

                    b.HasOne("Domain.Entities.Storyboard", "Storyboard")
                        .WithMany()
                        .HasForeignKey("StoryboardId")
                        .HasConstraintName("fk_scene_videos_storyboards_storyboard_id");

                    b.HasOne("Domain.Entities.Asset", "VideoAsset")
                        .WithMany()
                        .HasForeignKey("VideoAssetId")
                        .HasConstraintName("fk_scene_videos_assets_video_asset_id");

                    b.Navigation("Scene");

                    b.Navigation("Storyboard");

                    b.Navigation("VideoAsset");
                });

            modelBuilder.Entity("Domain.Entities.SceneVoice", b =>
                {
                    b.HasOne("Domain.Entities.Asset", "AudioAsset")
                        .WithMany()
                        .HasForeignKey("AudioAssetId")
                        .HasConstraintName("fk_scene_voices_assets_audio_asset_id");

                    b.HasOne("Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .HasConstraintName("fk_scene_voices_characters_character_id");

                    b.HasOne("Domain.Entities.Scene", "Scene")
                        .WithMany("Voices")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scene_voices_scenes_scene_id");

                    b.Navigation("AudioAsset");

                    b.Navigation("Character");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("Stories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stories_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Entities.Storyboard", b =>
                {
                    b.HasOne("Domain.Entities.Asset", "ImageAsset")
                        .WithMany()
                        .HasForeignKey("ImageAssetId")
                        .HasConstraintName("fk_storyboards_assets_image_asset_id");

                    b.HasOne("Domain.Entities.Scene", "Scene")
                        .WithOne("Storyboard")
                        .HasForeignKey("Domain.Entities.Storyboard", "SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storyboards_scenes_scene_id");

                    b.Navigation("ImageAsset");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Domain.Entities.Character", b =>
                {
                    b.Navigation("Appearance");

                    b.Navigation("Bible");

                    b.Navigation("Memories");

                    b.Navigation("Personality");

                    b.Navigation("Relationships");

                    b.Navigation("SceneCharacters");

                    b.Navigation("Voice");
                });

            modelBuilder.Entity("Domain.Entities.Location", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Navigation("AiGenerations");

                    b.Navigation("Assets");

                    b.Navigation("Characters");

                    b.Navigation("Locations");

                    b.Navigation("Stories");
                });

            modelBuilder.Entity("Domain.Entities.Scene", b =>
                {
                    b.Navigation("SceneCharacters");

                    b.Navigation("Storyboard");

                    b.Navigation("Video");

                    b.Navigation("Voices");
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.Navigation("FinalVideos");

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
