// <auto-generated />
using System;
using System.Text.Json;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApiCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_api_costs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_api_costs_created_at");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_api_costs_job_id");

                    b.HasIndex("Service")
                        .HasDatabaseName("ix_api_costs_service");

                    b.ToTable("api_costs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HookTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HookText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hook_text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<decimal?>("PerformanceScore")
                        .HasColumnType("numeric")
                        .HasColumnName("performance_score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hook_templates");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_hook_templates_category");

                    b.HasIndex("Language")
                        .HasDatabaseName("ix_hook_templates_language");

                    b.ToTable("hook_templates", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.JobVariation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text")
                        .HasColumnName("audio_url");

                    b.Property<string>("AvatarId")
                        .HasColumnType("text")
                        .HasColumnName("avatar_id");

                    b.Property<string>("AvatarVideoUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_video_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FinalUrl")
                        .HasColumnType("text")
                        .HasColumnName("final_url");

                    b.Property<string>("HookText")
                        .HasColumnType("text")
                        .HasColumnName("hook_text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("KlingTaskId")
                        .HasColumnType("text")
                        .HasColumnName("kling_task_id");

                    b.Property<Guid?>("ModelImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_image_id");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("output_format");

                    b.Property<string>("ProductVideoUrl")
                        .HasColumnType("text")
                        .HasColumnName("product_video_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<JsonDocument>("TryonImages")
                        .HasColumnType("jsonb")
                        .HasColumnName("tryon_images");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VariationIndex")
                        .HasColumnType("integer")
                        .HasColumnName("variation_index");

                    b.Property<string>("VoiceId")
                        .HasColumnType("text")
                        .HasColumnName("voice_id");

                    b.HasKey("Id")
                        .HasName("pk_job_variations");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_variations_job_id");

                    b.HasIndex("ModelImageId")
                        .HasDatabaseName("ix_job_variations_model_image_id");

                    b.ToTable("job_variations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ModelImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Ethnicity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ethnicity");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_url");

                    b.Property<string>("Style")
                        .HasColumnType("text")
                        .HasColumnName("style");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_model_images");

                    b.HasIndex("Gender")
                        .HasDatabaseName("ix_model_images_gender");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_model_images_is_active");

                    b.ToTable("model_images", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VideoJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text")
                        .HasColumnName("customer_email");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flow_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("output_format");

                    b.Property<string>("OutputUrl")
                        .HasColumnType("text")
                        .HasColumnName("output_url");

                    b.Property<JsonDocument>("ProductInfo")
                        .HasColumnType("jsonb")
                        .HasColumnName("product_info");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("text")
                        .HasColumnName("product_url");

                    b.Property<JsonDocument>("Script")
                        .HasColumnType("jsonb")
                        .HasColumnName("script");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TargetAudience")
                        .HasColumnType("text")
                        .HasColumnName("target_audience");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VideoType")
                        .HasColumnType("text")
                        .HasColumnName("video_type");

                    b.HasKey("Id")
                        .HasName("pk_video_jobs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_video_jobs_created_at");

                    b.HasIndex("FlowType")
                        .HasDatabaseName("ix_video_jobs_flow_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_video_jobs_status");

                    b.ToTable("video_jobs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ApiCost", b =>
                {
                    b.HasOne("Domain.Entities.VideoJob", "Job")
                        .WithMany("ApiCosts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_costs_video_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Domain.Entities.JobVariation", b =>
                {
                    b.HasOne("Domain.Entities.VideoJob", "Job")
                        .WithMany("Variations")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_variations_video_jobs_job_id");

                    b.HasOne("Domain.Entities.ModelImage", "ModelImage")
                        .WithMany()
                        .HasForeignKey("ModelImageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_job_variations_model_images_model_image_id");

                    b.Navigation("Job");

                    b.Navigation("ModelImage");
                });

            modelBuilder.Entity("Domain.Entities.VideoJob", b =>
                {
                    b.Navigation("ApiCosts");

                    b.Navigation("Variations");
                });
#pragma warning restore 612, 618
        }
    }
}
